name: Build
on:
  push:
    branches:
      - "**"

concurrency:
  group: build-${{ github.ref || github.run_id }}

jobs:
  release_pipeline:
    name: release_pipeline
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "build_validate.sh"
        run: |
          ./ci_cd/build_validate.sh
        shell: bash
      - name: "codesign_notarize.sh"
        run: |
          ./ci_cd/codesign_notarize.sh
        shell: bash
        env:
          MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: "upload_release.sh"
        if: startsWith(github.ref, 'refs/tags/v')
        run: ./ci_cd/upload_release.sh ${{ env.TAG_NAME }}
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ci_cd/bin/*
          retention-days: 30
